### ISSUE TITLE
Issue updating from 2.5.1.4 to 2.5.1.5 

### ISSUE THREAD

**Issue by Overseergti** [lmagyar/homeassistant-addon-mariadb-inmemory#19]
Getting this error when attempting to update:

`Can't install lmagyar/aarch64-addon-mariadb-inmemory:2.5.1.5: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.5.1.5&fromImage=lmagyar%2Faarch64-addon-mariadb-inmemory&platform=linux%2Farm64: Not Found ("manifest for lmagyar/aarch64-addon-mariadb-inmemory:2.5.1.5 not found: manifest unknown: manifest unknown")`

**Comment by lmagyar** [comment]
Oh, gosh, I see, this is on the `dev` branch... And this image is nonexistent, because it's under development...

When I changed the default branch of the repo to `master`, HA's Supervisor hasn't refreshed it's internal database...

Proof:
```
~ docker exec -it hassio_supervisor /bin/bash
bash-5.1# cd /data/addons/git/45207088/.git
bash-5.1# cat HEAD
ref: refs/heads/dev
```

## How to fix this (use the command line, eg. community ssh addon and putty):
```
docker ps                                                # just to test, that you have access to docker
ha core stop
ha backups new --addons 45207088_mariadb                 # WRITE DOWN (copy-paste) THE SLUG THAT IS PRINTED ON THE SCREEN
ha addons uninstall 45207088_mariadb
ha store delete 45207088
ha store add https://github.com/lmagyar/homeassistant-addon-mariadb-inmemory
ha addons install 45207088_mariadb
ha backups restore xxxxxxxx --addons 45207088_mariadb    # !!!!!!!! USE THE SLUG FROM THE BACKUP COMMAND ABOVE !!!!!!!!
ha core stop                                             # due to the restore, HA restarted, I think this is a bug in Supervisor, this messes up the database content
docker kill addon_45207088_mariadb                       # YES, KILL, the previously restored database export/dump will NOT be overwritten this way with the messed up database content
ha addons start 45207088_mariadb                         # usually unnecessary, but harmless, the add-on is restarted if watchdog is turned on
ha addons log 45207088_mariadb                           # check multiple times, that the log's end looks like this below, ie. the add-on is REALLY started, it can take up to 1 minute!

[12:42:22] INFO: Importing database content
s6-rc: info: service mariadb-core-post successfully started
s6-rc: info: service mariadb-backup: starting
s6-rc: info: service crond: starting
s6-rc: info: service mariadb-backup successfully started
s6-rc: info: service crond successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

ha core start
```

**Comment by Overseergti** [comment]
Sorry, I'm not sure I understand.

Do I need to run those commands, or are you working on an update that will fix this for me?

**Comment by lmagyar** [comment]
Yes, we need to run those commands in the CLI to get rid of this error forever.

If you can wait for the next version, just wait a few days.

Situation:
- HA remembers the outdated default branch name from this repo (I've changed it, I didn't know about this bug in HA), and I can't find a way to refresh it, only by completely removing and reinstalling the add-on. These are the commands above.
- Now HA thinks that my "under development" new version is released. :(
- I will try not to trigger this behavior in the future, not to modify the config.yaml file, only immediately before the release, so maybe I won't trigger this error too often if somebody doesn't reinstall the add-on. Sorry for the inconvenience, I'm also just a tinkerer, who sometimes messes up some things.

---

For those who use only the UI:
- Use this if the current database content is not important.
- Save the current configuration of the add-on. (Settings / Add-ons / In-memory MariaDB / Configuration tab / ... menu on the right side / Edit in YAML / copy-paste it somewhere)
- Uninstall the add-on. (Settings / Add-ons / In-memory MariaDB / Info tab / Uninstall )
- Remove the repository. (Settings / Add-ons / Add-on store / ... menu / Repositories / In-memory MariaDB add-on / Trash icon)
- Add again the repository. (Settings / Add-ons / Add-on store / ... menu / Repositories / Add https://github.com/lmagyar/homeassistant-addon-mariadb-inmemory)
- Install the add-on. (Settings / Add-ons / Add-on store / In-memory MariaDB add-on / Info tab / Install)
- Restore the configuration (what was copy-pasted previously)
- Start the add-on. (Settings / Add-ons / In-memory MariaDB / Info tab / Start)
- Restart HA core (Setting / System / Restart)
- NOTE: I didn't executed these UI steps myself. Though I'm sure there will be a lot of error messages from the recorder component in the HA log, that the database is not available during this reinstallation.
