### ISSUE TITLE
"Unknown storage engine 'InnoDB'"

### ISSUE THREAD

**Issue by lmagyar** [lmagyar/homeassistant-addon-mariadb-inmemory#24]
New tables got hard wired into recorder code in HA, like:

```
CREATE TABLE event_types (
	event_type_id INTEGER NOT NULL AUTO_INCREMENT, 
	event_type VARCHAR(64), 
	PRIMARY KEY (event_type_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci
```

I have to rewrite queries on the fly, to delete `ENGINE=InnoDB`...

Until it's done, please install original maridb add-on or restore previous HA version 2023.03.x.

**Comment by lmagyar** [comment]
I have run out of ideas. :(

Modifying SQL query statements, coming from HA, on the fly can't be done:
- MariaDB has no rewrite filter capability like MySQL https://dev.mysql.com/doc/refman/8.0/en/rewriter-query-rewrite-plugin-usage.html and it will be never done https://jira.mariadb.org/browse/MDEV-5561
- ProxySQL, MySQL Proxy, MySQL Router can't run on Alpine or abandoned
- NGINX and HAProxy cant rewrite MySQL protocol (only HTTP)
- Letting HA create the table with InnoDB storage engine and later modify it will fail because of the foreign key constraints Aria can't handle

The only way I see now is to forget Aria storage engine, use InnoDB, even if it uses 1.5-2x more disk space = memory. :(

The trick is to convert the current Aria backups back to InnoDB.

**Comment by Traxeronus** [comment]
Hi @lmagyar,
will you then continue with the change to InnoDB? I have a plenty of RAM, so it is not a blocker for me. Now I'm running without recorder because of the issue.
Thanks!

**Comment by lmagyar** [comment]
Hi, InnoDB has a serious flaw (storage leak): ibdata1 file grows out of control, no limit.

All the upvoted stackoverflow answers are wrong (backup, delete, restore workaround nonsense), but finally there is a solution: https://stackoverflow.com/a/72122560/2755656

Now I'm running tests, it seems InnoDB's overhead (with lowest possible settings) is about 50MB and it is finally seems to be CONSTANT.

I make a final test, update docs and release a new version soon.

**Comment by Traxeronus** [comment]
Can't install ghcr.io/lmagyar/amd64-addon-mariadb-inmemory-beta:2.5.2.3: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=2.5.2.3&fromImage=ghcr.io%2Flmagyar%2Famd64-addon-mariadb-inmemory-beta&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

**Comment by lmagyar** [comment]
Oh gosh, there were out a wrong config file for a few seconds, what already got cached...

`ha store reload` usually solves the problem, but now I've re-released the same binary again with a new version number.

**Comment by lmagyar** [comment]
I'm closing this as this is working now.
