### ISSUE TITLE
Install add-on in HA docker version

### ISSUE THREAD

**Issue by lv913** [lmagyar/homeassistant-addon-mariadb-inmemory#35]
I use HA running in a docker container. Unfortunately, on this version add-on button is not available and I need a manual procedure to install MariaDB in-memory add-on.
Can you please provide it?

**Comment by lmagyar** [comment]
If you run HA Container (see: https://www.home-assistant.io/installation/#compare-installation-methods), it is not possible to use add-ons. Even add-ons are docker images, but they require a few stuff around them to run (HA and Supervisor APIs, managed configuration options, backup/restore system, etc.), so add-ons can't be used if you installed HA Container.
